title: Karina Aquino Cantero
logo: /assets/img/github.png
description: "Hello ğŸŒ¼, I am an engineer with a passion for data and coding ğŸ‘©â€ğŸ’». As a dedicated data scientist, I thrive on exploring innovative approaches and continuous learning, particularly within Natural Language Processing (NLP) projects. My expertise lies in leveraging data to uncover insights and develop solutions, driving impactful outcomes."
show_downloads: true
theme: jekyll-theme-minimal
